### ISSUE TITLE
[PE-D] able to take the same mod twice

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-2/tp#139] opened 2021-10-30 16:24 UTC
![image.png](https://raw.githubusercontent.com/jon-the-melon/ped/main/files/a3d0b75b-f154-42fd-bd04-28c71fcd1904.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: jon-the-melon/ped#6

**Comment by ChewyChair** [comment] 2021-11-08 04:21
Duplicate of #162

**Closed by ChewyChair** 2021-11-08 04:21 UTC
