### ISSUE TITLE
[PE-D] "delete" command is accepted by program

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-2/tp#176] opened 2021-10-30 19:42 UTC
![12.JPG](https://raw.githubusercontent.com/pragyan01/ped/main/files/6aff0abf-9d45-4379-a59d-e305e9e6a5a9.JPG)
the command "delete" is accepted by program and prints "..is successfully removed from your transcript" which doesnt make sense.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: pragyan01/ped#13

**Comment by ChewyChair** [comment] 2021-11-07 05:27
Duplicate of #135

**Closed by ChewyChair** 2021-11-07 05:27 UTC
