### ISSUE TITLE
[PE-D] searching for a mod with -mc flag yields confusing result

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-2/tp#120] opened 2021-10-30 15:18 UTC
![1.JPG](https://raw.githubusercontent.com/pragyan01/ped/main/files/ea04405b-b8a5-4030-859d-fddd06dd1da2.JPG)

"search cs2113t -mc 3" prints a number 3, followed by the correct answer of 0 in the next line. the first printing of "3" is not needed and can be confusing.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: pragyan01/ped#1

**Comment by ChewyChair** [comment] 2021-10-31 08:11
Duplicate of #115

**Closed by ChewyChair** 2021-10-31 08:11 UTC
